### ISSUE TITLE
'exiting' class how can I change this class name? Option in environment.js? And why if I click to destroy flash the class is not applied?

### ISSUE THREAD

**Issue by mrkongo** [adopted-ember-addons/ember-cli-flash#206]
'exiting' class: how can I change this class name? Option in environment.js maybe?

And why if I click to destroy flash the class is not applied?

**Comment by oligriffiths** [comment]
+1

**Comment by sbatson5** [comment]
> And why if I click to destroy flash the class is not applied?

This has since been addressed--exiting class is applied when clicking.

We can certainly make the exiting class configurable.

**Comment by miguelcobain** [comment]
Making the exiting class configurable is especially useful when used with tailwind. +1
