### ISSUE TITLE
type definitions do not work / are not detected

### ISSUE THREAD

**Issue by NullVoxPopuli** [adopted-ember-addons/ember-cli-flash#348]
Repro steps:
1. ember new my-app
1.1 cd my-app
2. ember install ember-cli-typescript
3. ember install ember-cli-flash
4. create a file that imports from ember-cli-flash, such as: 
```ts
import FlashService from 'ember-cli-flash/services/flash-messages';

type MyOptions = Parameters<FlashService['add']>[0] & {
  buttons?: string[];
}

export default class FalconFlashService extends FlashService {
  add(options: MyOptions) {
    // custom stuff
    // // ...
    return super.add(options);
  }
}
```
5. Observe the error (both in-editor and via `tsc --build`):
```
app/services/flash-messages.ts:1:26 - error TS2307: Cannot find module 'ember-cli-flash/services/flash-messages' or its corresponding type declarations.

1 import FlashService from 'ember-cli-flash/services/flash-messages';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by simonihmig** [comment]
Same here. 

AFAIK TS looks for `node_modules/ember-cli-flash/services/flash-messages.d.ts` when trying to resolve the types for this module. But this does not exist. For the `declare module` statements to work, you need to explicitly make TS aware of the `index.d.ts`. I managed to do that by adding this to the `paths` section of my `tsconfig.json`:

```json
"ember-cli-flash/*": [
  "node_modules/ember-cli-flash"
],
```

That's ok as a workaround for now, but types working properly out of the box would be nice!

**Comment by ewal** [comment]
I solved it by creating a declaration file in the `types` folder with the path `types/ember-cli-flash/services/flash-messages/index.d.ts` and content:
```js
declare module 'ember-cli-flash/services/flash-messages' {
  import FlashMessageService from 'ember-cli-flash';
  export default class FlashMessageService {}
}

```

Import the service like this:
```js
import FlashMessageService from 'ember-cli-flash/services/flash-messages';
...
  @service declare flashMessages: FlashMessageService;
...
```

And presto :)
<img width="940" alt="image" src="https://user-images.githubusercontent.com/676873/165158598-191cf6b6-99ce-44b4-bfa0-e3c89e8f6b9b.png">

But yeah, would be great if the declaration file would be moved to where it used 👍

**Comment by charlesfries** [comment]
This seems to be fixed for me in `ember-cli-flash@5.0.0`. However the `FlashMessage` component is still not detected/not exported from this addon's TS declarations.

**Comment by Techn1x** [comment]
> This seems to be fixed for me in ember-cli-flash@5.0.0. However the FlashMessage component is still not detected/not exported from this addon's TS declarations.

**Comment by NullVoxPopuli** [comment]
Components exist in 5.1 
![image](https://github.com/adopted-ember-addons/ember-cli-flash/assets/199018/05a15ced-2ab4-4943-8acc-1a89531638cf)

**Comment by Techn1x** [comment]
I'm on 5.1.0 - that's the dist folder, the declarations for components don't show up

**Comment by NullVoxPopuli** [comment]
what's supposed to be in this folder?
![image](https://github.com/adopted-ember-addons/ember-cli-flash/assets/199018/f182dda0-5db5-4cf7-bdb1-5de32729fe89)

**Comment by Techn1x** [comment]
Oops! You're totally correct. I initially checked on an outdated branch that was v5.0.0, and then when I went to verify again an hour ago the ember-cli-flash version, I was on my main branch which renovate just updated to 5.1.0 overnight 😅 

I can indeed see the ember-cli-flash declarations for component in the published output

Also, didn't know could check published output via NPM page! That is handy

**Comment by NullVoxPopuli** [comment]
woo woo! I'll close this issue!
