### ISSUE TITLE
Cut a major 3.0 release

### ISSUE THREAD

**Issue by bartocc** [adopted-ember-addons/ember-cli-flash#375]
ember-cli-flash@2.2.0 includes PR #373, which includes a dep on `ember-cli-flash >= 2`.
Upgrading from ember-cli-flash@2.1.0 to ember-cli-flash@2.2.0 does not work on apps that depend on `ember-auto-import@1.x`

See my comment here https://github.com/poteto/ember-cli-flash/pull/373#issuecomment-1004860518

**Comment by Techn1x** [comment]
@sbatson5 might also want to cut a patch version for 2.2.x that reverts the changes as well.

**Comment by sbatson5** [comment]
Sorry for the mistake. Version 2.2.2 was pushed with the reverted changes.

Version 3.0.0 was released

**Comment by rwwagner90** [comment]
Should there be a changelog entry for 3.0.0? I'm having trouble finding what the changes were.

**Comment by sbatson5** [comment]
I would ping @stukalin for that contribution. I am really just keeping the lights on as I have admin access until the repo gets transferred. Would greatly appreciate a PR with those updates!

**Comment by rwwagner90** [comment]
@sbatson5 @stukalin we should setup release-it with automatic changelog and release generation. We should also get this repo transferred to adopted-ember-addons perhaps/

**Comment by rahulk94** [comment]
Transferring to the `adopted-ember-addons` org is the right thing here.

I believe @poteto reached out about doing that per https://github.com/poteto/ember-cli-flash/pull/365#issuecomment-963116400. Any updates on this?

**Comment by rwwagner90** [comment]
@sbatson5 if you have admin access, could you transfer the repo to me? I can then transfer it to adopted-ember-addons

**Comment by sbatson5** [comment]
> @sbatson5 if you have admin access, could you transfer the repo to me? I can then transfer it to adopted-ember-addons

I do not have admin access. Just contributor

**Comment by rwwagner90** [comment]
@poteto Could you please transfer the repo to me, so I could transfer to adopted-ember-addons?

**Comment by poteto** [comment]
@rwwagner90 Sorry about the delay! You'll need to delete your fork first, otherwise I can't transfer.

**Comment by rwwagner90** [comment]
@poteto done, thanks for responding and thank you for agreeing to transfer! Also, I'm not sure the best way to get in touch with you these days, but we would love to have you on our podcast! If you might be interested, please email me at robbie@shipshape.io

**Comment by RobbieTheWagner** [comment]
We released 4.0.0, so this can be closed.
