### ISSUE TITLE
Deprecations in Ember v4.0+

### ISSUE THREAD

**Issue by sandydoo** [adopted-ember-addons/ember-cli-flash#378]
Here’s a list of issues I’ve encountered in Ember 4.0:

- [ ] #379
	[`assign` is deprecated](https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign). This needs to be replaced with either Object.assign or the spread operator.
- [ ] #380 
	[Implicit injection was deprecated and is now disabled in 4.0](https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign). Lauren [deprecated injection 6 years ago](https://github.com/poteto/ember-cli-flash/commit/0e16ba81009097b8cd5121c4cd6eafa57b2c0618), so I would vote for removing the feature entirely. 
	Also, it’s kind of weird that injection is still enabled by default! I had no idea it was still on and had to explicitly set `injectionFactories: []` in my config to disable it.

**Comment by bartocc** [comment]
What is the status on this?

**Comment by charlesfries** [comment]
Any updates on this? @poteto @sbatson5
